name: Update Space Shooter GIF
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create assets directory
        run: mkdir -p assets
      - uses: czl9707/gh-space-shooter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: assets/space-shooter.gif
          strategy: random
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/space-shooter.gif
          git commit -m "chore: update space shooter gif" || exit 0
          git pull --rebase origin main
          git push